// +build  linux

// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  probe

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CapsetSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CapsetSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( CapsetSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CapsetSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CapsetSerializer *CapsetSerializer

func ( ContainerContextSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ContainerContextSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( ContainerContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ContainerContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ContainerContextSerializer *ContainerContextSerializer

func ( CredentialsSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CredentialsSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( CredentialsSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CredentialsSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CredentialsSerializer *CredentialsSerializer

func ( EventContextSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventContextSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( EventContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventContextSerializer *EventContextSerializer

func ( EventSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( EventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventSerializer *EventSerializer

func ( FileEventSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FileEventSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( FileEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FileEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FileEventSerializer *FileEventSerializer

func ( FileSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FileSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( FileSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FileSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FileSerializer *FileSerializer

func ( ProcessCacheEntrySerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ProcessCacheEntrySerializer ) UnmarshalJSON([]byte) error { return nil }
func ( ProcessCacheEntrySerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ProcessCacheEntrySerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProcessCacheEntrySerializer *ProcessCacheEntrySerializer

func ( ProcessContextSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ProcessContextSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( ProcessContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ProcessContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProcessContextSerializer *ProcessContextSerializer

func ( ProcessCredentialsSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ProcessCredentialsSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( ProcessCredentialsSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ProcessCredentialsSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProcessCredentialsSerializer *ProcessCredentialsSerializer

func ( SetgidSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SetgidSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( SetgidSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SetgidSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetgidSerializer *SetgidSerializer

func ( SetuidSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SetuidSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( SetuidSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SetuidSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetuidSerializer *SetuidSerializer

func ( UserContextSerializer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UserContextSerializer ) UnmarshalJSON([]byte) error { return nil }
func ( UserContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UserContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UserContextSerializer *UserContextSerializer
